# Generated by Django 4.2.5 on 2023-09-24 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverisement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='adverisement',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Было создано'),
        ),
        migrations.AlterField(
            model_name='adverisement',
            name='updated_add',
            field=models.DateTimeField(auto_now=True, verbose_name='Было обновлено'),
        ),
    ]
