# Generated by Django 4.2.5 on 2023-09-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0002_adverisement_user_alter_adverisement_created_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverisement',
            name='image',
            field=models.ImageField(default='', upload_to='lesson4/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
